'use strict';
const fs = require('node:fs');
const path = require('node:path');

const CONFIG_DIR = path.join(process.env.HOME || process.env.USERPROFILE, '.vault-cli');
const LANG_FILE = path.join(CONFIG_DIR, 'lang');
const SUPPORTED = ['en', 'it'];
const DEFAULT_LANGUAGE = 'en';

const strings = {
  en: {
    'node.tooOld': 'Node.js {version} detected: Node.js {min} or newer is required.',
    'node.openingDownload': 'Opening the Node.js download page in your browser...',
    'node.manualDownload': 'Go to https://nodejs.org to download an up-to-date version.',
    'free.login': 'Free mode active: Vault CLI does not require an account or login.',
    'free.logout': 'Free mode active: there is no login to disconnect.',
    'free.whoami': 'free mode',
    'free.account': 'Free mode active: no account is needed to use Vault CLI.',
    'menu.back': '← Back',
    'menu.accountTitle': 'Account:',
    'doctor.title': '--- Vault Doctor ---',
    'doctor.node': 'Node.js: v{version}',
    'doctor.npm': 'npm: {version}',
    'doctor.config': 'Configuration: {path} ({state})',
    'doctor.configPresent': 'present',
    'doctor.configMissing': 'not created',
    'doctor.r2Configured': 'Cloud R2: configured',
    'doctor.r2NotConfigured': 'Cloud R2: not configured (use "vault cloud")',
    'doctor.account': 'Account: free mode, no login required.',
    'doctor.permissions': 'Folder permissions: OK',
    'doctor.systemReady': 'System: ready.',
    'doctor.problem': 'Problem detected: {message}',
    'desc.program': 'Vault Semplice CLI — Explorer & Archive Edition',
    'desc.start': 'Opens the Vault Semplice interactive interface',
    'desc.login': 'Activates free mode with no account',
    'desc.logout': 'Shows that free mode does not use accounts',
    'desc.whoami': 'Shows that the CLI is running in free mode',
    'desc.create': 'Encrypts a file and creates a .vault',
    'opt.output': 'output .vault file path',
    'opt.password': 'password (if omitted, it is asked securely)',
    'opt.expires': 'ISO expiry date/time, e.g. 2026-12-31T23:59:00Z',
    'opt.maxOpens': 'maximum number of opens (0 = unlimited)',
    'opt.security': 'security level: standard | high | maximum',
    'opt.pdf': 'generate a summary PDF after creation',
    'desc.open': 'Decrypts a .vault and restores the original file',
    'opt.outputOpen': 'output path (default: original file name)',
    'desc.info': 'Shows the metadata of a .vault without decrypting it',
    'desc.securityLevels': 'Lists the available security levels',
    'desc.update': 'Automatically updates the CLI to the latest version',
    'desc.uninstall': 'Completely removes Vault from the computer',
    'desc.doctor': 'Checks for configuration problems',
    'desc.config': 'Shows the current settings',
    'desc.cloud': 'Configures R2 cloud access',
    'desc.status': 'Shows the current status of the CLI',
    'desc.lang': 'Shows or changes the CLI language (en/it)',
    'lang.current': 'Current language: {language}',
    'lang.usage': 'Usage: vault lang <en|it>',
    'lang.changed': 'Language set to: {language}',
    'lang.unsupported': 'Unsupported language "{language}". Available: {supported}',
    'status.version': 'Version: {version}',
    'status.platform': 'Platform: {platform}',
    'status.directory': 'Directory: {directory}',
    'status.account': 'Account: free mode, no login required',
    'action.fileNotFound': 'File not found: {file}',
    'action.emptyPassword': 'Empty password not allowed',
    'action.setPassword': 'Set a password: ',
    'action.password': 'Password: ',
    'action.invalidDate': 'Invalid date',
    'action.vaultCreated': 'Vault created: {path} ({bytes} bytes encrypted) — security: {level}',
    'action.pdfGenerated': 'Summary PDF generated: {path}',
    'action.fileRestored': 'File restored: {path}',
    'menu.maxOpensTitle': 'Maximum number of times the vault can be opened:',
    'menu.maxOpensUnlimited': 'Unlimited',
    'menu.maxOpensOne': '1 open',
    'menu.maxOpensN': '{n} opens',
    'menu.maxOpensCustom': 'Custom...',
    'menu.maxOpensAsk': 'How many opens do you want to allow at most?',
    'menu.expiryTitle': 'Vault expiry:',
    'menu.expiryNone': 'No expiry',
    'menu.expiryDay': 'In 1 day',
    'menu.expiryDays': 'In {n} days',
    'menu.expiryCustom': 'Custom date...',
    'menu.expiryAsk': 'Expiry date/time (e.g. 2026-12-31T23:59:00Z)',
    'menu.securityTitle': 'Security level:',
    'prompt.chooseOption': 'Choose an option (number)',
    'prompt.invalidChoice': 'Invalid choice, try again.',
    'prompt.cancelled': 'Cancelled',
    'banner.subtitle': 'encrypt, protect, share',
    'crypto.invalidVault': 'Invalid or unrecognized .vault file',
    'crypto.expired': 'This vault has expired',
    'crypto.maxOpensReached': 'Maximum number of opens reached',
    'crypto.wrongPassword': 'Wrong password or corrupted file',
    'interactive.dashboardTitle': 'VAULT 2.0 DASHBOARD',
    'interactive.dashboardSubtitle': 'Explorer • Folders • Key file • Compression • Integrity • Cloud R2',
    'interactive.loggedInAs': 'Signed in as {email}',
    'interactive.menuTitle': 'What do you want to do?',
    'interactive.menuCreate': 'Create a new vault',
    'interactive.menuCreateHint': 'encrypt a file',
    'interactive.menuOpen': 'Open a vault',
    'interactive.menuOpenHint': 'decrypt a file',
    'interactive.menuInfo': 'Vault info',
    'interactive.menuExplorer': 'Vault Explorer and v2 archives',
    'interactive.menuExplorerHint': 'use: vault folder / list / tree / search / extract',
    'interactive.menuTools': 'Security and tools',
    'interactive.menuToolsHint': 'password / hash / verify / benchmark / rekey',
    'interactive.menuCloud': 'Cloud R2',
    'interactive.menuCloudHint': 'push / pull / ls / rm',
    'interactive.menuDoctor': 'System diagnostics',
    'interactive.menuLang': 'Change language',
    'interactive.menuExit': 'Exit',
    'interactive.explorerInfo': 'Explorer commands: vault folder <folder>, vault list <vault>, vault tree <vault>, vault search <vault> <text>, vault extract <vault>',
    'interactive.toolsInfo': 'Security commands: vault password, vault hash <file>, vault verify <vault>, vault benchmark, vault rekey <vault>',
    'interactive.goodbye': 'See you soon!',
    'interactive.askFileToEncrypt': 'Path of the file to encrypt',
    'interactive.confirmPdf': 'Generate a summary PDF at the end?',
    'interactive.askVaultToOpen': 'Path of the .vault file to open',
    'interactive.askVaultPath': 'Path of the .vault file',
    'interactive.cloudTitle': 'Cloud R2:',
    'interactive.cloudPush': 'Upload a file (push)',
    'interactive.cloudPull': 'Download a file (pull)',
    'interactive.cloudLs': 'List files (ls)',
    'interactive.cloudRm': 'Delete a file (rm)',
    'interactive.askLocalFileUpload': 'Local file to upload',
    'interactive.askRemoteKeyOptional': 'Remote key (enter = file name)',
    'interactive.uploadedToR2': 'Uploaded to R2: {key} ({bytes} bytes)',
    'interactive.askRemoteKeyDownload': 'Remote key to download',
    'interactive.askOutputPathOptional': 'Local output path (enter = file name)',
    'interactive.downloadedFromR2': 'Downloaded from R2: {path} ({bytes} bytes)',
    'interactive.askPrefixOptional': 'Prefix (enter = all)',
    'interactive.noFilesFound': '(no files found)',
    'interactive.askRemoteKeyDelete': 'Remote key to delete',
    'interactive.deletedFromR2': 'Deleted from R2: {key}',
  },
  it: {
    'node.tooOld': 'Node.js {version} rilevato: è richiesto Node.js {min} o superiore.',
    'node.openingDownload': 'Apro la pagina di download di Node.js nel browser...',
    'node.manualDownload': 'Vai su https://nodejs.org per scaricare una versione aggiornata.',
    'free.login': 'Modalità gratuita attiva: Vault CLI non richiede account o login.',
    'free.logout': 'Modalità gratuita attiva: non c’è alcun login da disconnettere.',
    'free.whoami': 'modalità gratuita',
    'free.account': 'Modalità gratuita attiva: non serve alcun account per usare Vault CLI.',
    'menu.back': '← Indietro',
    'menu.accountTitle': 'Account:',
    'doctor.title': '--- Vault Doctor ---',
    'doctor.node': 'Node.js: v{version}',
    'doctor.npm': 'npm: {version}',
    'doctor.config': 'Configurazione: {path} ({state})',
    'doctor.configPresent': 'presente',
    'doctor.configMissing': 'non creata',
    'doctor.r2Configured': 'Cloud R2: configurato',
    'doctor.r2NotConfigured': 'Cloud R2: non configurato (usa "vault cloud")',
    'doctor.account': 'Account: modalità gratuita, nessun login richiesto.',
    'doctor.permissions': 'Permessi cartelle: OK',
    'doctor.systemReady': 'Sistema: pronto.',
    'doctor.problem': 'Problema rilevato: {message}',
    'desc.program': 'Vault Semplice CLI — Explorer & Archive Edition',
    'desc.start': 'Apre l’interfaccia interattiva di Vault Semplice',
    'desc.login': 'Attiva la modalità gratuita senza account',
    'desc.logout': 'Mostra che la modalità gratuita non usa account',
    'desc.whoami': 'Mostra che la CLI è in modalità gratuita',
    'desc.create': 'Cifra un file e crea un .vault',
    'opt.output': 'percorso file .vault di output',
    'opt.password': 'password (se omessa, viene chiesta in modo sicuro)',
    'opt.expires': 'data/ora di scadenza ISO, es. 2026-12-31T23:59:00Z',
    'opt.maxOpens': 'numero massimo di aperture (0 = illimitato)',
    'opt.security': 'livello di sicurezza: standard | alta | massima',
    'opt.pdf': 'genera un PDF di riepilogo dopo la creazione',
    'desc.open': 'Decifra un .vault e ripristina il file originale',
    'opt.outputOpen': 'percorso di output (default: nome file originale)',
    'desc.info': 'Mostra i metadati di un .vault senza decifrarlo',
    'desc.securityLevels': 'Elenca i livelli di sicurezza disponibili',
    'desc.update': 'Aggiorna automaticamente la CLI alla versione più recente',
    'desc.uninstall': 'Rimuove completamente Vault dal computer',
    'desc.doctor': 'Controlla eventuali problemi di configurazione',
    'desc.config': 'Mostra le impostazioni attuali',
    'desc.cloud': "Configura l'accesso al cloud R2",
    'desc.status': 'Mostra lo stato attuale della CLI',
    'desc.lang': 'Mostra o cambia la lingua della CLI (en/it)',
    'lang.current': 'Lingua attuale: {language}',
    'lang.usage': 'Uso: vault lang <en|it>',
    'lang.changed': 'Lingua impostata su: {language}',
    'lang.unsupported': 'Lingua "{language}" non supportata. Disponibili: {supported}',
    'status.version': 'Versione: {version}',
    'status.platform': 'Piattaforma: {platform}',
    'status.directory': 'Directory: {directory}',
    'status.account': 'Account: modalità gratuita, nessun login richiesto',
    'action.fileNotFound': 'File non trovato: {file}',
    'action.emptyPassword': 'Password vuota non consentita',
    'action.setPassword': 'Imposta una password: ',
    'action.password': 'Password: ',
    'action.invalidDate': 'Data non valida',
    'action.vaultCreated': 'Vault creato: {path} ({bytes} byte cifrati) — sicurezza: {level}',
    'action.pdfGenerated': 'PDF di riepilogo generato: {path}',
    'action.fileRestored': 'File ripristinato: {path}',
    'menu.maxOpensTitle': 'Numero massimo di aperture del vault:',
    'menu.maxOpensUnlimited': 'Illimitate',
    'menu.maxOpensOne': '1 apertura',
    'menu.maxOpensN': '{n} aperture',
    'menu.maxOpensCustom': 'Personalizzato...',
    'menu.maxOpensAsk': 'Quante aperture massime vuoi consentire?',
    'menu.expiryTitle': 'Scadenza del vault:',
    'menu.expiryNone': 'Nessuna scadenza',
    'menu.expiryDay': 'Tra 1 giorno',
    'menu.expiryDays': 'Tra {n} giorni',
    'menu.expiryCustom': 'Data personalizzata...',
    'menu.expiryAsk': 'Data/ora di scadenza (es. 2026-12-31T23:59:00Z)',
    'menu.securityTitle': 'Livello di sicurezza:',
    'prompt.chooseOption': 'Scegli un’opzione (numero)',
    'prompt.invalidChoice': 'Scelta non valida, riprova.',
    'prompt.cancelled': 'Annullato',
    'banner.subtitle': 'cifra, proteggi, condividi',
    'crypto.invalidVault': 'File .vault non valido o non riconosciuto',
    'crypto.expired': 'Questo vault è scaduto',
    'crypto.maxOpensReached': 'Numero massimo di aperture raggiunto',
    'crypto.wrongPassword': 'Password errata o file corrotto',
    'interactive.dashboardTitle': 'DASHBOARD VAULT 2.0',
    'interactive.dashboardSubtitle': 'Explorer • Cartelle • Key file • Compressione • Integrità • Cloud R2',
    'interactive.loggedInAs': 'Accesso effettuato come {email}',
    'interactive.menuTitle': 'Cosa vuoi fare?',
    'interactive.menuCreate': 'Crea un nuovo vault',
    'interactive.menuCreateHint': 'cifra un file',
    'interactive.menuOpen': 'Apri un vault',
    'interactive.menuOpenHint': 'decifra un file',
    'interactive.menuInfo': 'Info su un vault',
    'interactive.menuExplorer': 'Vault Explorer e archivi v2',
    'interactive.menuExplorerHint': 'usa: vault folder / list / tree / search / extract',
    'interactive.menuTools': 'Sicurezza e strumenti',
    'interactive.menuToolsHint': 'password / hash / verify / benchmark / rekey',
    'interactive.menuCloud': 'Cloud R2',
    'interactive.menuCloudHint': 'push / pull / ls / rm',
    'interactive.menuDoctor': 'Diagnostica sistema',
    'interactive.menuLang': 'Cambia lingua',
    'interactive.menuExit': 'Esci',
    'interactive.explorerInfo': 'Comandi Explorer: vault folder <cartella>, vault list <vault>, vault tree <vault>, vault search <vault> <testo>, vault extract <vault>',
    'interactive.toolsInfo': 'Comandi sicurezza: vault password, vault hash <file>, vault verify <vault>, vault benchmark, vault rekey <vault>',
    'interactive.goodbye': 'A presto!',
    'interactive.askFileToEncrypt': 'Percorso del file da cifrare',
    'interactive.confirmPdf': 'Generare un PDF di riepilogo alla fine?',
    'interactive.askVaultToOpen': 'Percorso del file .vault da aprire',
    'interactive.askVaultPath': 'Percorso del file .vault',
    'interactive.cloudTitle': 'Cloud R2:',
    'interactive.cloudPush': 'Carica un file (push)',
    'interactive.cloudPull': 'Scarica un file (pull)',
    'interactive.cloudLs': 'Elenca i file (ls)',
    'interactive.cloudRm': 'Elimina un file (rm)',
    'interactive.askLocalFileUpload': 'File locale da caricare',
    'interactive.askRemoteKeyOptional': 'Chiave remota (invio = nome file)',
    'interactive.uploadedToR2': 'Caricato su R2: {key} ({bytes} byte)',
    'interactive.askRemoteKeyDownload': 'Chiave remota da scaricare',
    'interactive.askOutputPathOptional': 'Percorso locale di output (invio = nome file)',
    'interactive.downloadedFromR2': 'Scaricato da R2: {path} ({bytes} byte)',
    'interactive.askPrefixOptional': 'Prefisso (invio = tutti)',
    'interactive.noFilesFound': '(nessun file trovato)',
    'interactive.askRemoteKeyDelete': 'Chiave remota da eliminare',
    'interactive.deletedFromR2': 'Eliminato da R2: {key}',
  },
};

let currentLanguage = null;

function loadLanguage() {
  if (currentLanguage) return currentLanguage;
  try {
    if (fs.existsSync(LANG_FILE)) {
      const saved = fs.readFileSync(LANG_FILE, 'utf8').trim();
      if (SUPPORTED.includes(saved)) {
        currentLanguage = saved;
        return currentLanguage;
      }
    }
  } catch {
    // Ignore unreadable config, fall back to the default language below.
  }
  currentLanguage = DEFAULT_LANGUAGE;
  return currentLanguage;
}

function setLanguage(lang) {
  if (!SUPPORTED.includes(lang)) {
    throw new Error(t('lang.unsupported', { language: lang, supported: SUPPORTED.join(', ') }));
  }
  currentLanguage = lang;
  try {
    if (!fs.existsSync(CONFIG_DIR)) fs.mkdirSync(CONFIG_DIR, { recursive: true });
    fs.writeFileSync(LANG_FILE, lang);
  } catch {
    // Best effort: the language still applies for the current process.
  }
}

function t(key, vars = {}) {
  const lang = loadLanguage();
  const template = (strings[lang] && strings[lang][key]) || strings[DEFAULT_LANGUAGE][key] || key;
  return Object.entries(vars).reduce((text, [name, value]) => text.split(`{${name}}`).join(value), template);
}

module.exports = { t, setLanguage, loadLanguage, SUPPORTED, DEFAULT_LANGUAGE };
